---
# tasks file for configure-lab/win-common
- name: Assert mandatory variables have been set
  assert: { that: "{{ item }} is defined" }
  with_items:
    - windows_common_win_psmodule_required
    - windows_common_win_service_delayed_required
    - windows_common_win_power_plan
    - windows_common_win_dns_client_adapter_names
    - windows_common_win_dns_client_ipv4_addresses
    - windows_common_win_hostname_name

- name: Ensure that required DSC resources and Powershell Modules are present
  win_psmodule:
    name: "{{ item }}"
    state: present
  with_items: "{{ windows_common_win_psmodule_required }}"

- name: Ensure that required services are set to start when the system has settled
  win_service:
    name: WinRM
    start_mode: delayed
  with_items: "{{ windows_common_win_service_delayed_required }}"

- name: Ensure we use the {{ windows_common_win_power_plan }} power plan
  win_power_plan:
    name: "{{ windows_common_win_power_plan }}"

- name: Ensure upstream DNS servers are set on the adapter named {{ windows_common_win_dns_client_adapter_names }}
  win_dns_client:
   adapter_names: "{{ windows_common_win_dns_client_adapter_names }}"
   ipv4_addresses: "{{ windows_common_win_dns_client_ipv4_addresses }}"

- name: Ensure hostname is set to {{ windows_common_win_hostname_name }}
  win_hostname:
    name: "{{ windows_common_win_hostname_name }}"
  register: rename

- name: Reboot
  win_reboot:
  when: rename.reboot_required