---
# tasks file for ansible-role-wincom
- name: Assert mandatory variables have been set
  ansible.builtin.assert: { that: "{{ item }} is defined" }
  with_items:
    - wincom_required_psmodule
    - wincom_service_delayed
    - wincom_power_plan
    - wincom_dns_nics
    - wincom_dns_servers
    - wincom_hostname

- name: Ensure that required DSC resources and Powershell Modules are present
  ansible.windows.win_psmodule:
    name: "{{ item }}"
    state: present
  with_items: "{{ wincom_required_psmodule }}"

- name: Ensure that required services are set to start when the system has settled
  ansible.windows.win_service:
    name: "{{ item }}"
    start_mode: delayed
  with_items: "{{ wincom_service_delayed }}"

- name: Ensure we use the {{ wincom_power_plan }} power plan
  ansible.windows.win_power_plan:
    name: "{{ wincom_power_plan }}"

- name: Ensure upstream DNS servers are set on the adapter named {{ wincom_dns_nics }}
  ansible.windows.win_dns_client:
   adapter_names: "{{ wincom_dns_nics }}"
   ipv4_addresses: "{{ wincom_dns_servers }}"

- name: Ensure hostname is set correctly
  ansible.windows.win_hostname:
    name: "{{ wincom_hostname }}"
  register: rename

- name: Reboot
  ansible.windows.win_reboot:
  when: rename.reboot_required
